language: ruby
notifications:
  email:
    - paul4hough@gmail.com

#bundler_args: --without development
#script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
#rvm:
# - 1.8.7
# - 1.9.3
#  - 2.0.0
#env:
# - PUPPET_GEM_VERSION="~> 2.7.0"
#  - PUPPET_GEM_VERSION="~> 3.2.0"
#matrix:
#  exclude:
# - rvm: 1.9.3
# env: PUPPET_GEM_VERSION="~> 2.7.0"
#    - rvm: 2.0.0
#      env: PUPPET_GEM_VERSION="~> 2.7.0"
#branches:
#  only:
#    - devel-pah
#    - master
#
# before_script:
#   - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#   - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#
#script: "bundle exec rake -t lint unittest_prep unittest_suite"
script: "env; echo hi travis; exit 2"